In [2]:
import numpy as np

# Membuat array pertama
a = np.array([[1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 2],
              [1, 6, 1, 1]], dtype=int)
print(a)

# Membuat array kedua
b = np.array([[0., 0., 0., 0., 0.],
              [2., 0., 0., 0., 0.],
              [0., 3., 0., 0., 0.],
              [0., 0., 4., 0., 0.],
              [0., 0., 0., 5., 0.],
              [0., 0., 0., 0., 6.]], dtype=float)
print(b)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 6 1 1]]
[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]
