In [1]:
import numpy as np

# Membuat array dengan menggunakan arange
a = np.arange(6)
print(a)

# Membuat array dengan menggunakan arange
b = np.arange(0, 51, 10)[:, np.newaxis]
print(b)

# Penjumlahan dua array
c = a + b
print(c)

# Slicing array untuk mendapatkan bilangan ganjil menghitung mundur
d = c[:, 5:0:-2]  # Menggunakan start, end, dan step
print(d)

# Slicing array untuk mendapatkan bilangan genap menghitung maju
e = c[:, 1:6:2]  # Menggunakan start, end, dan step
print(e)

# Slicing array dengan menggunakan slicing bawaan Python
f = c[:, ::-1]  # Menghitung mundur dengan step -1
print(f)
g = c[:, ::2]  # Menghitung maju dengan step 2
print(g)


[9. 7. 5. 3. 1.]
[1. 3. 5. 7. 9.]
[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
[0. 2. 4. 6. 8.]
